### PR TITLE
Improve benchmarks

### PR DESCRIPTION
**Pull request by weiznich**
* Use criterion for benchmarks
* Add some more useful benchmarks
    + Batch insert
    + relation benchmarks
* Some minor sql improvements for diesel, sqlx and postgres
* Improve dataset insertion for diesel, sqlx and postgres
* allow to disable certain crates via feature flags

### CODE REVIEW

**Comment by sanpii** [comment]
Thanks for your help!

I massively rewrite my code since you wrote this PR. It'd probably be easier to split this PR.

I already cherry picked 909b05e, 37eaa28 and cc924a7.

Concerning the performance improvements of `fetch_first` and `fetch_last`, it is voluntary not to use `limit`/`offset` SQL statement.

**Comment by weiznich** [comment]
> Concerning the performance improvements of fetch_first and fetch_last, it is voluntary not to use limit/offset SQL statement.

In that case I do not really see any meaning in such a benchmark then. At least for `fetch_last` this is basically equivalent to `query_all` then.

> I massively rewrite my code since you wrote this PR. It'd probably be easier to split this PR.

That's quite unfortunate, as the performance improvements for batch inserting the data into the database are quite massive.
Adapting the newly written benchmarks to the new structure should be quite easy. Adapting the criterion change seems harder, but that's definitively something you should consider.

**Comment by weiznich** [comment]
> Concerning the performance improvements of fetch_first and fetch_last, it is voluntary not to use limit/offset SQL statement.

In that case I do not really see any meaning in such a benchmark then. At least for `fetch_last` this is basically equivalent to `query_all` then.

> I massively rewrite my code since you wrote this PR. It'd probably be easier to split this PR.

That's quite unfortunate, as the performance improvements for batch inserting the data into the database are quite massive.
Adapting the newly written benchmarks to the new structure should be quite easy. Adapting the criterion change seems harder, but that's definitively something you should consider.

**Comment by sanpii** [comment]
> In that case I do not really see any meaning in such a benchmark then. At least for `fetch_last` this is basically equivalent to `query_all` then.

Not necessarily, `libpq` allows to check out an arbitrary result without load all.

> Adapting the criterion change seems harder, but that's definitively something you should consider.

Yes, I just discover this crate, it looks nice. I am working to cherry pick this commit.

**Comment by sanpii** [comment]
e21e8f0 is rebased in the [criterion](https://github.com/elephantry/benchmark/tree/criterion) branch, but performance improvement are welcome before…

**Comment by weiznich** [comment]
> Not necessarily, libpq allows to check out an arbitrary result without load all.

That's true, but in that case you should call the corresponding method (`first` or `get_result` for `fetch_first) for diesel and not just collect everything and then using a index. (There is no such method for `fetch_last` because I don't think that is useful for the general case).

As another interesting sidenote: At least `sqlx` and `postgres` have their own implementation of the libpq protocol. It's quite interesting that they perform roughly as well as diesel/libpq for basically all workloads.

> but performance improvement are welcome before…

The relevant lines for 
* [Diesel](https://github.com/elephantry/benchmark/pull/1/commits/2b1df108bb1224907d522794821942f15a26da89#diff-6030e165f2ec0b6fe28dde9a70069121R54-R61)
* [Sqlx](https://github.com/elephantry/benchmark/pull/1/commits/9d4e85ae5971d677c1e68455e4d48a6fec064843#diff-8517ad0a1c0ef4b003dc579c684e254eR38-R57)
* [Postgres](https://github.com/elephantry/benchmark/pull/1/commits/535dc5c34f2a0e3250c80f97922b6b90a1efd49e#diff-af3ccd1217c1a88a23842bae2eed7033R46-R61)

Also adding the benchmarks from https://github.com/elephantry/benchmark/pull/1/commits/d5db3139f4c8ac7d1fe33f336032f3536b259467 and https://github.com/elephantry/benchmark/pull/1/commits/765faf345e5c4a37c4b6d91f4ad00005d6e509b2 should be interesting.

**Comment by weiznich** [comment]
Mostly merged to master already.

**Pull request closed without merging**
